import{ Info } from './info'
export const bookdesc: Info[] = [
    { id: 1101, name: "The Alchemist", author: "Paulo Coelho", price: 150, desc: "Paulo Coelho's enchanting novel has inspired a devoted following around the world. This story, dazzling in its powerful simplicity and soul-stirring wisdom, is about an Andalusian shepherd boy named Santiago who travels from his homeland in Spain to the Egyptian desert in search of a treasure buried near the Pyramids. Along the way he meets a Gypsy woman, a man who calls himself king, and an alchemist, all of whom point Santiago in the direction of his quest. No one knows what the treasure is, or if Santiago will be able to surmount the obstacles in his path. But what starts out as a journey to find worldly goods turns into a discovery of the treasure found within. Lush, evocative, and deeply humane, the story of Santiago is an eternal testament to the transforming power of our dreams and the importance of listening to our hearts.",image:"./assets/Images/alchemist.jpg" },
    { id: 1102, name: "1984", author: "George Orwell", price: 180, desc: "Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its futuristic purgatory becomes more real. Published in 1949, the book offers political satirist George Orwell's nightmarish vision of a totalitarian, bureaucratic world and one poor stiff's attempt to find individuality. The brilliance of the novel is Orwell's prescience of modern life—the ubiquity of television, the distortion of the language—and his ability to construct such a thorough version of hell. Required reading for students since it was published, it ranks among the most terrifying novels ever written.", image:"./assets/Images/1984.jpg" },
    { id: 1103, name: "The Great Gatsby", author: "F. Scott Fitzgerald", price: 220, desc: "Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its futuristic purgatory becomes more real. Published in 1949, the book offers political satirist George Orwell's nightmarish vision of a totalitarian, bureaucratic world and one poor stiff's attempt to find individuality. The brilliance of the novel is Orwell's prescience of modern life—the ubiquity of television, the distortion of the language—and his ability to construct such a thorough version of hell. Required reading for students since it was published, it ranks among the most terrifying novels ever written.",image:"./assets/Images/gatsby.jpg" },
    { id: 1104, name: "The Old Man and the Sea", author: "Ernest Hemingway", price: 230, desc: "The last novel Ernest Hemingway saw published, The Old Man and the Sea has proved itself to be one of the enduring works of American fiction. It is the story of an old Cuban fisherman and his supreme ordeal: a relentless, agonizing battle with a giant marlin far out in the Gulf Stream. Using the simple, powerful language of a fable, Hemingway takes the timeless themes of courage in the face of defeat and personal triumph won from loss and transforms them into a magnificent twentieth-century classic.",image:"./assets/Images/oldman.jpg" },
    { id: 1105, name: "The Hobbit  There and Back Again", author: "J.R.R. Tolkien", price: 200, desc: "Chess Story, also known as The Royal Game, is the Austrian master Stefan Zweig's final achievement, completed in Brazilian exile and sent off to his American publisher only a matter of days before his suicide in 1942. It is the only story in which Zweig looks at Nazism, and he does so with characteristic emphasis on the psychological.",image:"./assets/Images/hobbit.jpg" },
    { id: 1106, name: "Murder on the Orient Express", author: "Agatha Christie", price: 190, desc: "Chess Story, also known as The Royal Game, is the Austrian master Stefan Zweig's final achievement, completed in Brazilian exile and sent off to his American publisher only a matter of days before his suicide in 1942. It is the only story in which Zweig looks at Nazism, and he does so with characteristic emphasis on the psychological.",image:"./assets/Images/orient.jpg" },
    { id: 1107, name: "The Little Prince", author: "Antoine de Saint-Exupéry,", price: 110, desc: "Chess Story, also known as The Royal Game, is the Austrian master Stefan Zweig's final achievement, completed in Brazilian exile and sent off to his American publisher only a matter of days before his suicide in 1942. It is the only story in which Zweig looks at Nazism, and he does so with characteristic emphasis on the psychological.",image:"./assets/Images/price.jpg" },
    { id: 1108, name: "The Metamorphosis", author: "Franz Kafka", price: 170, desc: "Chess Story, also known as The Royal Game, is the Austrian master Stefan Zweig's final achievement, completed in Brazilian exile and sent off to his American publisher only a matter of days before his suicide in 1942. It is the only story in which Zweig looks at Nazism, and he does so with characteristic emphasis on the psychological.",image:"./assets/Images/meta.jpg" },
    { id: 1109, name: "A Study in Scarlet", author: "Arthur Conan Doyle", price: 100, desc: "Chess Story, also known as The Royal Game, is the Austrian master Stefan Zweig's final achievement, completed in Brazilian exile and sent off to his American publisher only a matter of days before his suicide in 1942. It is the only story in which Zweig looks at Nazism, and he does so with characteristic emphasis on the psychological.",image:"./assets/Images/blade.jpg" },
    { id: 1110, name: "Do Androids Dream of Electric Sheep?", author: "Philip K. Dick", price: 360, desc: "Chess Story, also known as The Royal Game, is the Austrian master Stefan Zweig's final achievement, completed in Brazilian exile and sent off to his American publisher only a matter of days before his suicide in 1942. It is the only story in which Zweig looks at Nazism, and he does so with characteristic emphasis on the psychological.",image:"./assets/Images/sherlock.jpg" },
    { id: 1111, name: "Chess Story", author: "Stefan Zweig", price: 200, desc: "Chess Story, also known as The Royal Game, is the Austrian master Stefan Zweig's final achievement, completed in Brazilian exile and sent off to his American publisher only a matter of days before his suicide in 1942. It is the only story in which Zweig looks at Nazism, and he does so with characteristic emphasis on the psychological.",image:"./assets/Images/chess.jpg" },
    { id: 1112, name: "The Time Machine", author: "H.G. Wells", price: 450, desc: "Chess Story, also known as The Royal Game, is the Austrian master Stefan Zweig's final achievement, completed in Brazilian exile and sent off to his American publisher only a matter of days before his suicide in 1942. It is the only story in which Zweig looks at Nazism, and he does so with characteristic emphasis on the psychological.",image:"./assets/Images/time.jpg" },
    
]

